const AccountInitData = [
  {
      "Name": "红星科技有限公司",
      "BillingStreet": "北京市海淀区中关村大街1号",
      "BillingCity": "北京",
      "BillingState": "北京市",
      "BillingPostalCode": "100080",
      "BillingCountry": "中国",
      "ShippingStreet": "北京市海淀区中关村大街1号",
      "ShippingCity": "北京",
      "ShippingState": "北京市",
      "ShippingPostalCode": "100080",
      "ShippingCountry": "中国",
      "Phone": "+86 10 1234 5678",
      "Fax": "+86 10 1234 5679",
      "AccountNumber": "AC002",
      "Website": "www.redstar.com",
      "Sic": "7372",
      "AnnualRevenue": "8000000",
      "NumberOfEmployees": "400",
      "TickerSymbol": "RS",
      "Description": "红星科技有限公司是一家专注于IT解决方案的公司。",
      "Site": "www.redstar.com",
      "Acronym__c": "RS",
      "Logo__c": "logo_url",
      "LastFollowupDate__c": NOW_DATE,
  },
  {
      "Name": "绿源环保科技有限公司",
      "BillingStreet": "广州市天河区珠江新城5号",
      "BillingCity": "广州",
      "BillingState": "广东省",
      "BillingPostalCode": "510000",
      "BillingCountry": "中国",
      "ShippingStreet": "广州市天河区珠江新城5号",
      "ShippingCity": "广州",
      "ShippingState": "广东省",
      "ShippingPostalCode": "510000",
      "ShippingCountry": "中国",
      "Phone": "+86 20 1234 5678",
      "Fax": "+86 20 1234 5679",
      "AccountNumber": "AC003",
      "Website": "www.greenresource.com",
      "Sic": "7372",
      "AnnualRevenue": "9000000",
      "NumberOfEmployees": "450",
      "TickerSymbol": "GR",
      "Description": "绿源环保科技有限公司是一家专注于环保科技的公司。",
      "Site": "www.greenresource.com",

      "Acronym__c": "GR",
      "Logo__c": "logo_url",
    
      "LastFollowupDate__c": NOW_DATE,
   
  },
  {
      "Name": "蓝海科技有限公司",
      "BillingStreet": "深圳市南山区高新科技园1号",
      "BillingCity": "深圳",
      "BillingState": "广东省",
      "BillingPostalCode": "518000",
      "BillingCountry": "中国",
      "ShippingStreet": "深圳市南山区高新科技园1号",
      "ShippingCity": "深圳",
      "ShippingState": "广东省",
      "ShippingPostalCode": "518000",
      "ShippingCountry": "中国",
      "Phone": "+86 755 1234 5678",
      "Fax": "+86 755 1234 5679",
      "AccountNumber": "AC004",
      "Website": "www.blueocean.com",
      "Sic": "7372",
      "AnnualRevenue": "12000000",
      "NumberOfEmployees": "600",
      "TickerSymbol": "BO",
      "Description": "蓝海科技有限公司是一家专注于AI科技的公司。",
      "Site": "www.blueocean.com",
      
      "Acronym__c": "BO",
      "Logo__c": "logo_url",
       
      "LastFollowupDate__c":NOW_DATE,
      
  },
  {
      "Name": "金光科技有限公司",
      "BillingStreet": "杭州市滨江区网商路599号",
      "BillingCity": "杭州",
      "BillingState": "浙江省",
      "BillingPostalCode": "310000",
      "BillingCountry": "中国",
      "ShippingStreet": "杭州市滨江区网商路599号",
      "ShippingCity": "杭州",
      "ShippingState": "浙江省",
      "ShippingPostalCode": "310000",
      "ShippingCountry": "中国",
      "Phone": "+86 571 1234 5678",
      "Fax": "+86 571 1234 5679",
      "AccountNumber": "AC005",
      "Website": "www.goldlight.com",
      "Sic": "7372",
      "AnnualRevenue": "13000000",
      "NumberOfEmployees": "650",
      "TickerSymbol": "GL",
      "Description": "金光科技有限公司是一家专注于新能源科技的公司。",
      "Site": "www.goldlight.com",
      
      "Acronym__c": "GL",
      "Logo__c": "logo_url",
       
      "LastFollowupDate__c": NOW_DATE, 
  },
  {
      "Name": "紫光科技有限公司",
      "BillingStreet": "南京市鼓楼区中山北路66号",
      "BillingCity": "南京",
      "BillingState": "江苏省",
      "BillingPostalCode": "210000",
      "BillingCountry": "中国",
      "ShippingStreet": "南京市鼓楼区中山北路66号",
      "ShippingCity": "南京",
      "ShippingState": "江苏省",
      "ShippingPostalCode": "210000",
      "ShippingCountry": "中国",
      "Phone": "+86 25 1234 5678",
      "Fax": "+86 25 1234 5679",
      "AccountNumber": "AC006",
      "Website": "www.purplelight.com",
      "Sic": "7372",
      "AnnualRevenue": "11000000",
      "NumberOfEmployees": "550",
      "TickerSymbol": "PL",
      "Description": "紫光科技有限公司是一家专注于云计算科技的公司。",
      "Site": "www.purplelight.com",
      "CustomerPriority__c": "High",
      "SLA__c": "Gold",
      "Active__c": "Yes",
       
      "Acronym__c": "PL",
      "Logo__c": "logo_url",
       
      "LastFollowupDate__c":NOW_DATE,
     
  },
  {
      "Name": "海尔科技有限公司",
      "BillingStreet": "青岛市市南区南京路1号",
      "BillingCity": "青岛",
      "BillingState": "山东省",
      "BillingPostalCode": "266000",
      "BillingCountry": "中国",
      "ShippingStreet": "青岛市市南区南京路1号",
      "ShippingCity": "青岛",
      "ShippingState": "山东省",
      "ShippingPostalCode": "266000",
      "ShippingCountry": "中国",
      "Phone": "+86 532 1234 5678",
      "Fax": "+86 532 1234 5679",
      "AccountNumber": "AC007",
      "Website": "www.haier.com",
      "Sic": "7372",
      "AnnualRevenue": "14000000",
      "NumberOfEmployees": "700",
      "TickerSymbol": "HR",
      "Description": "海尔科技有限公司是一家专注于家电科技的公司。",
      "Site": "www.haier.com",
       
      "Acronym__c": "HR",
      "Logo__c": "logo_url",
      
      "LastFollowupDate__c":NOW_DATE,

  },
  {
      "Name": "联想科技有限公司",
      "BillingStreet": "北京市海淀区中关村大街6号",
      "BillingCity": "北京",
      "BillingState": "北京市",
      "BillingPostalCode": "100080",
      "BillingCountry": "中国",
      "ShippingStreet": "北京市海淀区中关村大街6号",
      "ShippingCity": "北京",
      "ShippingState": "北京市",
      "ShippingPostalCode": "100080",
      "ShippingCountry": "中国",
      "Phone": "+86 10 1234 5670",
      "Fax": "+86 10 1234 5671",
      "AccountNumber": "AC008",
      "Website": "www.lenovo.com",
      "Sic": "7372",
      "AnnualRevenue": "15000000",
      "NumberOfEmployees": "750",
      "TickerSymbol": "LV",
      "Description": "联想科技有限公司是一家专注于计算机科技的公司。",
      "Site": "www.lenovo.com",
      
      "Acronym__c": "LV",
      "Logo__c": "logo_url",
       
      "LastFollowupDate__c": NOW_DATE,
     
  },
  {
      "Name": "华为科技有限公司",
      "BillingStreet": "深圳市龙岗区坂田华为基地",
      "BillingCity": "深圳",
      "BillingState": "广东省",
      "BillingPostalCode": "518000",
      "BillingCountry": "中国",
      "ShippingStreet": "深圳市龙岗区坂田华为基地",
      "ShippingCity": "深圳",
      "ShippingState": "广东省",
      "ShippingPostalCode": "518000",
      "ShippingCountry": "中国",
      "Phone": "+86 755 1234 5680",
      "Fax": "+86 755 1234 5681",
      "AccountNumber": "AC009",
      "Website": "www.huawei.com",
      "Sic": "7372",
      "AnnualRevenue": "16000000",
      "NumberOfEmployees": "800",
      "TickerSymbol": "HW",
      "Description": "华为科技有限公司是一家专注于通信科技的公司。",
      "Site": "www.huawei.com",
       
      "Acronym__c": "HW",
      "Logo__c": "logo_url",
      
      "LastFollowupDate__c": NOW_DATE,
      
  },
  {
      "Name": "阿里巴巴科技有限公司",
      "BillingStreet": "杭州市西湖区西溪路699号",
      "BillingCity": "杭州",
      "BillingState": "浙江省",
      "BillingPostalCode": "310000",
      "BillingCountry": "中国",
      "ShippingStreet": "杭州市西湖区西溪路699号",
      "ShippingCity": "杭州",
      "ShippingState": "浙江省",
      "ShippingPostalCode": "310000",
      "ShippingCountry": "中国",
      "Phone": "+86 571 1234 5682",
      "Fax": "+86 571 1234 5683",
      "AccountNumber": "AC010",
      "Website": "www.alibaba.com",
      "Sic": "7372",
      "AnnualRevenue": "17000000",
      "NumberOfEmployees": "850",
      "TickerSymbol": "AB",
      "Description": "阿里巴巴科技有限公司是一家专注于电子商务科技的公司。",
      "Site": "www.alibaba.com",
       
      "Acronym__c": "AB",
      "Logo__c": "logo_url",
       
      "LastFollowupDate__c": NOW_DATE,
      
  }
]

module.exports = {
  AccountInitData
}