const LeadInitData = [
  {
      "LastName": "王",
      "FirstName": "春梅",
      "Salutation": "Ms.",
      "Title": "销售经理",
      "Company": "京东科技有限公司",
      "Street": "北京市朝阳区",
      "State": "BJ",
      "PostalCode": "100020",
      "Country": "CHA",
      "Phone": "(010) 1234-5678",
      "MobilePhone": "13800138000",
      "Fax": "(010) 1234-5679",
      "Email": "wangchunmei@jd.com",
      "Website": "http://www.jd.com",
      "Description": "客户需要一套营销系统，要求包括客户管理、订单管理、库存管理等模块",
      "Status": "Open - Not Contacted",
      "Industry": "E-commerce",
      "AnnualRevenue": 500750000,
      "NumberOfEmployees": null,
   
  },
  {
      "LastName": "杨",
      "FirstName": "冬梅",
      "Salutation": "Ms.",
      "Title": "人事经理",
      "Company": "新浪科技有限公司",
      "Street": "上海市浦东新区",
      "State": "SH",
      "PostalCode": "200120",
      "Country": "CHA",
      "Phone": "(021) 1234-5678",
      "MobilePhone": "13900139000",
      "Fax": "(021) 1234-5679",
      "Email": "yangdongmei@sina.com",
      "Website": "http://www.sina.com",
      "Description": "客户需要一套人力资源系统，要求包括员工管理、薪资管理、考勤管理等模块",
      "Status": "Open - Not Contacted",
      "Industry": "Internet",
      "AnnualRevenue": 600750000,
      "NumberOfEmployees": null,
  },
  {
      "LastName": "赵",
      "FirstName": "新军",
      "Salutation": "Mr.",
      "Title": "总经理",
      "Company": "携程科技有限公司",
      "Street": "上海市长宁区",
      "State": "SH",
      "PostalCode": "200050",
      "Country": "CHA",
      "Phone": "(021) 2234-5678",
      "MobilePhone": "13600136000",
      "Fax": "(021) 2234-5679",
      "Email": "zhaoxinjun@ctrip.com",
      "Website": "http://www.ctrip.com",
      "Description": "客户需要一套旅游系统，要求包括旅游景点管理、订单管理、客户管理等模块",
      "Status": "Open - Not Contacted",
      "Industry": "Travel",
      "AnnualRevenue": 700750000,
      "NumberOfEmployees": null,
  },
  {
      "LastName": "吴",
      "FirstName": "亦凡",
      "Salutation": "Mr.",
      "Title": "财务经理",
      "Company": "阿里巴巴科技有限公司",
      "Street": "杭州市西湖区",
      "State": "ZJ",
      "PostalCode": "310000",
      "Country": "CHA",
      "Phone": "(0571) 1234-5678",
      "MobilePhone": "13700137000",
      "Fax": "(0571) 1234-5679",
      "Email": "wuyifan@alibaba.com",
      "Website": "http://www.alibaba.com",
      "Description": "客户需要一套财务系统，要求包括会计管理、财务报表、费用管理等模块",
      "Status": "Open - Not Contacted",
      "Industry": "E-commerce",
      "AnnualRevenue": 800750000,
      "NumberOfEmployees": null,
  },
  {
      "LastName": "张",
      "FirstName": "丽丽",
      "Salutation": "Ms.",
      "Title": "人事经理",
      "Company": "腾讯科技有限公司",
      "Street": "深圳市南山区",
      "State": "GD",
      "PostalCode": "518000",
      "Country": "CHA",
      "Phone": "(0755) 1234-5678",
      "MobilePhone": "13600136000",
      "Fax": "(0755) 1234-5679",
      "Email": "zhanglili@tencent.com",
      "Website": "http://www.tencent.com",
      "Description": "客户需要一套人力资源系统，要求包括员工管理、薪资管理、考勤管理等模块",
      "Status": "Open - Not Contacted",
      "Industry": "Internet",
      "AnnualRevenue": 900750000,
      "NumberOfEmployees": null,
  },
  {
      "LastName": "叶",
      "FirstName": "秋",
      "Salutation": "Ms.",
      "Title": "项目经理",
      "Company": "百度科技有限公司",
      "Street": "北京市海淀区",
      "State": "BJ",
      "PostalCode": "100080",
      "Country": "CHA",
      "Phone": "(010) 2234-5678",
      "MobilePhone": "13500135000",
      "Fax": "(010) 2234-5679",
      "Email": "yeqiu@baidu.com",
      "Website": "http://www.baidu.com",
      "Description": "客户需要一套搜索引擎系统，要求包括搜索引擎优化、关键词管理、搜索结果管理等模块",
      "Status": "Open - Not Contacted",
      "Industry": "Internet",
      "AnnualRevenue": 1000750000,
      "NumberOfEmployees": null,
  },
  {
      "LastName": "李",
      "FirstName": "华",
      "Salutation": "Mr.",
      "Title": "总经理",
      "Company": "小米科技有限公司",
      "Street": "北京市海淀区",
      "State": "BJ",
      "PostalCode": "100080",
      "Country": "CHA",
      "Phone": "(010) 3234-5678",
      "MobilePhone": "13400134000",
      "Fax": "(010) 3234-5679",
      "Email": "lihua@xiaomi.com",
      "Website": "http://www.xiaomi.com",
      "Description": "客户需要一套生产管理系统，要求包括生产计划管理、生产进度管理、生产设备管理等模块",
      "Status": "Open - Not Contacted",
      "Industry": "Electronics",
      "AnnualRevenue": 1100750000,
      "NumberOfEmployees": null,
  }
]

module.exports = {
  LeadInitData
}