const OpportunityInitData = [
  {
      "IsPrivate": false,
      "Name": "星汉科技公司",
      "Description": "新型科技产品研发",
      "StageName": "Negotiation/Review",
      "Amount": 10000,
      "Probability": 50,
      "CloseDate": "2023-12-31",
      "Type": "Existing Customer",
      "NextStep": "Project Proposal",
      "LeadSource": "Web",
      "LastFollowupDate__c": NOW_DATE,
      "FollowupCountRecently__c": 2,
      "LostReason__c": "价格竞争"
  },
  {
      "IsPrivate": false,
      "Name": "梦飞信息技术公司",
      "Description": "网络安全服务",
      "StageName": "Proposal/Price Quote",
      "Amount": 20000,
      "Probability": 40,
      "CloseDate": "2024-06-01",
      "Type": "New Customer",
      "NextStep": "Final Review",
      "LeadSource": "Referral",
      "LastFollowupDate__c": NOW_DATE,
      "FollowupCountRecently__c": 3,
      "LostReason__c": "服务质量问题"
  },
  {
      "IsPrivate": false,
      "Name": "恒阳科技公司",
      "Description": "云计算服务",
      "StageName": "Closed Won",
      "Amount": 30000,
      "Probability": 80,
      "CloseDate": "2024-07-01",
      "Type": "Existing Customer",
      "NextStep": "Project Implementation",
      "LeadSource": "Partner",
      "LastFollowupDate__c": NOW_DATE,
      "FollowupCountRecently__c": 1,
      "LostReason__c": "合作伙伴关系问题"
  },
  {
      "IsPrivate": false,
      "Name": "盈大股份有限公司",
      "Description": "大数据解决方案",
      "StageName": "Closed Lost",
      "Amount": 40000,
      "Probability": 20,
      "CloseDate": "2024-08-01",
      "Type": "New Customer",
      "NextStep": "Re-negotiation",
      "LeadSource": "Trade Show",
      "LastFollowupDate__c":NOW_DATE,
      "FollowupCountRecently__c": 3,
      "LostReason__c": "产品性能不满足要求"
  },
  {
      "IsPrivate": false,
      "Name": "宇林峰信息有限公司",
      "Description": "移动应用开发",
      "StageName": "Negotiation/Review",
      "Amount": 50000,
      "Probability": 60,
      "CloseDate": "2024-09-01",
      "Type": "Existing Customer",
      "NextStep": "Contract Signing",
      "LeadSource": "Internal Referral",
      "LastFollowupDate__c": NOW_DATE,
      "FollowupCountRecently__c": 2,
      "LostReason__c": "交付时间问题"
  },
  {
      "IsPrivate": false,
      "Name": "环年光科技公司",
      "Description": "物联网解决方案",
      "StageName": "Closed Won",
      "Amount": 60000,
      "Probability": 70,
      "CloseDate": "2024-10-01",
      "Type": "New Customer",
      "NextStep": "Project Implementation",
      "LeadSource": "Webinar",
      "LastFollowupDate__c": NOW_DATE,
      "FollowupCountRecently__c": 1,
      "LostReason__c": "合作伙伴关系问题"
  },
  {
      "IsPrivate": false,
      "Name": "智源宇技术股份有限公司",
      "Description": "人工智能解决方案",
      "StageName": "Closed Lost",
      "Amount": 70000,
      "Probability": 30,
      "CloseDate": "2024-11-01",
      "Type": "Existing Customer",
      "NextStep": "Re-negotiation",
      "LeadSource": "Email",
      "LastFollowupDate__c": NOW_DATE,
      "FollowupCountRecently__c": 3,
      "LostReason__c": "价格竞争"
  },
  {
      "IsPrivate": false,
      "Name": "泰亨巨源科技有限公司",
      "Description": "数字化转型服务",
      "StageName": "Negotiation/Review",
      "Amount": 80000,
      "Probability": 50,
      "CloseDate": "2024-12-01",
      "Type": "New Customer",
      "NextStep": "Contract Signing",
      "LeadSource": "Partner",
      "LastFollowupDate__c": NOW_DATE,
      "FollowupCountRecently__c": 2,
      "LostReason__c": "服务质量问题"
  }
]

module.exports = {
  OpportunityInitData
}